// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// Polls
export const GET_POLLS_LIST_SUCCESS = 'GET_POLLS_LIST_SUCCESS';
export const GET_POLLS_LIST_FAIL = 'GET_POLLS_LIST_FAIL';
export const GET_POLLS_LIST_CATEGORIES_SUCCESS = 'GET_POLLS_LIST_CATEGORIES_SUCCESS';
export const GET_POLLS_LIST_CATEGORIES_FAIL = 'GET_POLLS_LIST_CATEGORIES_FAIL';
export const GET_POLL_SUCCESS = 'GET_POLL_SUCCESS';
export const GET_POLL_FAIL = 'GET_POLL_FAIL';

export const GET_POLLS_PAGINATION_RESULTS_SUCCESS = 'GET_POLLS_PAGINATION_RESULTS_SUCCESS';
export const GET_POLLS_PAGINATION_RESULTS_FAIL = 'GET_POLLS_PAGINATION_RESULTS_FAIL';

export const GET_SEARCH_POLL_SUCCESS = 'GET_SEARCH_POLL_SUCCESS';
export const GET_SEARCH_POLL_FAIL = 'GET_SEARCH_POLL_FAIL';