# Generated by Django 4.1.5 on 2023-02-06 23:49

import apps.polls.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('question_text', models.CharField(max_length=280)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to=apps.polls.models.question_directory_path)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('choice_text', models.CharField(max_length=220)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
